version: "3.9"

services:
  web:
    image: randomsummer/fake-webapp:latest   # ✅ use your own username
    container_name: fake_web
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/media

  db:
    image: postgres:15
    container_name: fake_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  static_volume:
  media_volume:

