name: SSH Smoke Test

on:
  workflow_dispatch:   # run manually from the Actions tab

jobs:
  ssh-test:
    runs-on: ubuntu-latest
    steps:
      - name: Print runner IP (useful if you restrict SSH by IP)
        run: curl -s https://api.ipify.org || true

      - name: SSH to server and run basic checks
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}      # e.g. deploy
          key: ${{ secrets.SSH_PRIVATE_KEY }}       # your github_actions PRIVATE key
          # port: ${{ secrets.SERVER_PORT }}        # uncomment if you use a non-22 port
          script: |
            set -e
            echo "=== whoami & hostname ==="
            whoami && hostname
            echo "=== OS & kernel ==="
            uname -a
            echo "=== Docker version ==="
            docker --version || echo "docker not found"
            echo "=== Docker Compose version ==="
            docker compose version || echo "compose not found"
            echo "=== Home dir listing ==="
            ls -la ~
            echo "=== App dir listing (~/fake) ==="
            ls -la ~/fake || echo "~/fake not found"
            echo "=== Done ==="
